name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ${{ github.repository_owner }}/gskit:latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        apk add build-base git

    - name: Install ps2stuff
      run: |
        git clone https://github.com/ps2dev/ps2stuff.git
        cd ps2stuff && make clean all install

    - name: Compile project
      run: |
        make DEBUG=1 && make install

    - name: Compile GLUT
      run: |
        cd glut && make DEBUG=1 && make install
    
    - name: Compile BOX example
      run: |
        cd examples/box && make DEBUG=1

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: box-${{ steps.slug.outputs.sha8 }}
        path: examples/box/box.elf
